---
title: "report9"
author: "Haoliang Zheng"
date: "12/24/2021"
output:
  pdf_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/zhl/Desktop/drdisc")
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = 'center', 
                      fig.width=6, fig.height=7)

library(abind)
library(knitr)
library(latex2exp)
require(magrittr)
require(plyr)
library(tidyverse)
library(coda)
library(doParallel)
library(doMC) 
library(foreach)
library(doRNG)

adapt <- FALSE
bunch <- FALSE
N_para <- 6

registerDoMC(6)
```


```{r source, include=FALSE}
source("./codes/new-codes.R")
source("./codes/test-codes.R")
source("./codes/other-codes.R")

multi_chain_coda_noa <- function(result_multi, burn = 1000, N_para, p, order){
  coda_result <- list()
  matrix_result <- NULL
  for(i in 1:N_para){
    matrix_result <- NULL
    for(j in 1:order){
      for(k in 1:p){
        bijk <- matrix(result_multi[[i]]$b[j,k,], ncol = 1)
        colnames(bijk) <- paste0("b",j,k)
        matrix_result <- cbind(matrix_result, bijk)
      }
    }
    coda_result[[i]] <- mcmc(matrix_result, start = burn+1)
  }
  coda_result_list <- mcmc.list(coda_result)
  
  return(coda_result_list)
}
```

# data

```{r}
vote <- read.csv("./codes/vote_data.csv")
str(vote)
vote <- subset(vote, abs(from_requirement_threshold) < 0.5)
set.seed(1234)
train.ss <- sample(nrow(vote), 15e3)

preds <- model.matrix(~ #major.requirement 
                        + ISS.against.recommendation 
                      #+ shares.oustanding.base 
                      #+ special.meeting 
                      + analyst.coverage 
                      #+ institutional.ownership 
                      + past.stock.return 
                      + q 
                      + firm.size, 
                      data = vote)[,-1]
preds.train <- scale(preds[train.ss,])
x <- cbind(1, preds.train)
x.test <- cbind(1, scale(preds[-train.ss,],
                         center=attr(preds.train,"scaled:center"),
                         scale=attr(preds.train,"scaled:scale")))
dimnames(x)[[2]][1] <- "Intercept"
dimnames(x.test)[[2]][1] <- "Intercept"
x.names <- dimnames(x)[[2]]

y <- 2*vote[train.ss,"from_requirement_threshold"]
y.test <- 2*vote[-train.ss,"from_requirement_threshold"]

bunch <- FALSE
pos.est <- TRUE
```

```{r}
N_para <- 6
p <- 6
set.seed(123)

b_init <- replicate(N_para, 
                    cbind(rnorm(n=5, sd=3), rnorm(n=5, sd=1.5), rnorm(n=5, sd=0.5),
                          rnorm(n=5, sd=0.25), rnorm(n=5, sd=0.15), rnorm(n=5, sd=0.5))
                    )
```

# algorithms, no alpha


```{r simxnew, cache=TRUE}
noa_multi <- foreach(i = 1:N_para) %dorng%
  bdregjump_noa(y=y, x=x, b=b_init[,,i], burn=2000, nsamp=10000, thin=1)
```

```{r}
save(noa_multi, y, x, b_init, file = "./report/report9/noa_multi.RData")
```

```{r}
load("./report/report9/noa_multi.RData")
noa_multi_coda <- multi_chain_coda_noa(noa_multi, N_para, p, 5)
plot(noa_multi_coda)
```

## order = 5


```{r}
set.seed(123)
order <- 5
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=3), order, p))

noa_o5_multi_new <- foreach(i = 1:N_para) %dorng%
  bdregjump_noa(y=y, x=x, b=b_init[,,i], burn=0, nsamp=5000, thin=1, order = order, print.process = TRUE)

save(noa_o5_multi_new, y, x, b_init, order, file = "./report/report9/noa_o5_multi_new.RData")
```

```{r}
noa_o5_multi_coda_new <- multi_chain_coda_noa(noa_o5_multi_new, N_para, p, order)
plot(noa_o5_multi_coda_new)
```

## order = 8


```{r}
set.seed(123)
order <- 8
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=3), order, p))

noa_o8_multi_new <- foreach(i = 1:N_para) %dorng%
  bdregjump_noa(y=y, x=x, b=b_init[,,i], burn=0, nsamp=5000, thin=1, order = order)

save(noa_o8_multi_new, y, x, b_init, order, file = "./report/report9/noa_o8_multi_new.RData")
```

```{r}
noa_o8_multi_coda_new <- multi_chain_coda_noa(noa_o8_multi_new, burn = 0, N_para, p, order)
plot(noa_o8_multi_coda_new)
```

## order = 10

```{r}
set.seed(123)
order <- 10
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=3), order, p))

noa_o10_multi_new <- foreach(i = 1:N_para) %dorng%
  bdregjump_noa(y=y, x=x, b=b_init[,,i], burn=0, nsamp=5000, thin=1, order = order)

save(noa_o10_multi_new, y, x, b_init, order, file = "./report/report9/noa_o10_multi_new.RData")
```

```{r}
noa_o10_multi_coda_new <- multi_chain_coda_noa(noa_o10_multi_new, burn = 0, N_para, p, order)
plot(noa_o10_multi_coda_new)
```


## order = 13

```{r}
set.seed(123)
order <- 13
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=3), order, p))

noa_o13_multi_new <- foreach(i = 1:N_para) %dorng%
  bdregjump_noa(y=y, x=x, b=b_init[,,i], burn=0, nsamp=5000, thin=1, order = order)

save(noa_o13_multi_new, y, x, b_init, order, file = "./report/report9/noa_o13_multi_new.RData")
```

```{r}
noa_o13_multi_coda_new <- multi_chain_coda_noa(noa_o13_multi_new, burn = 0, N_para, p, order)
plot(noa_o13_multi_coda_new)
```

## order = 13, new seed2

```{r}
set.seed(123)
order <- 13
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=5), order, p))

noa_o13_multi_new2 <- foreach(i = 1:N_para) %dorng%
  bdregjump_noa(y=y, x=x, b=b_init[,,i], burn=0, nsamp=5000, thin=1, order = order)

save(noa_o13_multi_new2, y, x, b_init, order, file = "./report/report9/noa_o13_multi_new2.RData")
```

```{r}
noa_o13_multi_coda_new2 <- multi_chain_coda_noa(noa_o13_multi_new2, burn = 0, N_para, p, order)
plot(noa_o13_multi_coda_new2)
```

## order = 15

```{r}
set.seed(123)
order <- 15
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=3), order, p))

noa_o15_multi_new <- foreach(i = 1:N_para) %dorng%
  bdregjump_noa(y=y, x=x, b=b_init[,,i], burn=0, nsamp=5000, thin=1, order = order)

save(noa_o15_multi_new, y, x, b_init, order, file = "./report/report9/noa_o15_multi_new.RData")
```

```{r}
noa_o15_multi_coda_new <- multi_chain_coda_noa(noa_o15_multi_new, burn = 0, N_para, p, order)
plot(noa_o15_multi_coda_new)
```


## order = 15, new seed2

```{r}
set.seed(123)
order <- 15
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=5), order, p))

noa_o15_multi_new2 <- foreach(i = 1:N_para) %dorng%
  bdregjump_noa(y=y, x=x, b=b_init[,,i], burn=0, nsamp=5000, thin=1, order = order)

save(noa_o15_multi_new2, y, x, b_init, order, file = "./report/report9/noa_o15_multi_new2.RData")
```

```{r}
noa_o15_multi_coda_new2 <- multi_chain_coda_noa(noa_o15_multi_new2, burn = 0, N_para, p, order)
plot(noa_o15_multi_coda_new2)
```


# adapt with order = 15

## initial

```{r}
set.seed(123)
N_para <- 6
p <- 6
order <- 15

kbw <- 2/(order-1)
knots <- seq(-1,1,kbw)
bsd.sq <- (0.67*kbw)^2
gausskern <- lapply(knots, function(mu) return(function(x) return(exp(-0.5*(x-mu)^2/bsd.sq))))
get.poly.mat <- function(y) return(sapply(gausskern, function(f) f(y)))

yFn <- get.poly.mat

b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=5), order, p))
a_init <- replicate(N_para, rnorm(n = p, sd = 1.5))
```

## result

```{r adapt_order15, cache=TRUE}
adapt_order15 <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt(y=y, x=x, b=b_init[,,i], burn=2000, nsamp=10000, thin=1, order = 15,
                  jump=list(a=a_init[,i], prec = 1/100, positive=pos.est, update.jbw=TRUE))
```

```{r}
save(adapt_order15, y, x, b_init, a_init, order, file = "./report/report9/adapt_order15.RData")
```

```{r}
adapt_order15_coda <- multi_chain_coda(adapt_order15, burn=2000, N_para, p, order)

plot(adapt_order15_coda)
gelman.diag(adapt_order15_coda)
```


### update.jbw = FALSE

```{r adapt_order15jbw, cache=TRUE}
adapt_order15_jbw <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt(y=y, x=x, b=b_init[,,i], burn=2000, nsamp=10000, thin=1, order = 15,
                  jump=list(a=a_init[,i], prec = 1/100, positive=pos.est,
                            persistence=0.68, update.jbw=FALSE))
```

```{r}
save(adapt_order15_jbw, y, x, b_init, a_init, order, file = "./report/report9/adapt_order15_jbw.RData")
```

```{r}
adapt_order15_jbw_coda <- multi_chain_coda(adapt_order15_jbw, burn=2000, N_para, p, order)

plot(adapt_order15_jbw_coda)

real_data_plot(adapt_order15_jbw[[1]], x, x.test, y.test, yFn)
```


### update.jbw = FALSE, alpha_star = 0.15

```{r adapt_order15jbw, cache=TRUE}
adapt_order15_jbw_alpha15 <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt(y=y, x=x, b=b_init[,,i], burn=2000, nsamp=10000, thin=1, order = 15,
                  jump=list(a=a_init[,i], prec = 1/100, positive=pos.est,
                            persistence=0.68, update.jbw=FALSE),
                  adap=list(alpha_star = 0.15))
```

```{r}
save(adapt_order15_jbw_alpha15, y, x, b_init, a_init, order, file = "./report/report9/adapt_order15_jbw_alpha15.RData")
```

```{r}
adapt_order15_jbw_alpha15_coda <- multi_chain_coda(adapt_order15_jbw_alpha15, burn=2000, N_para, p, order)

plot(adapt_order15_jbw_alpha15_coda)

for(i in 1:N_para){
  plot(adapt_order15_jbw_alpha15[[i]]$a[1,], type = "l")
}


real_data_plot(adapt_order15_jbw_alpha15[[1]], x, x.test, y.test, yFn)
real_data_plot(adapt_order15_jbw_alpha15[[2]], x, x.test, y.test, yFn)
real_data_plot(adapt_order15_jbw_alpha15[[5]], x, x.test, y.test, yFn)
```

### adapt_all

```{r adapt_order15all, cache=TRUE}
adapt_order15_all <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt_all(y=y, x=x, b=b_init[,,i], burn=2000, nsamp=10000, thin=1, order = 15,
                  jump=list(a=a_init[,i], prec = 1/100, positive=pos.est, update.jbw=TRUE),
                  adap=list(chol.pivot=TRUE))
```

```{r}
save(adapt_order15_all, y, x, b_init, a_init, order, file = "./report/report9/adapt_order15_all.RData")
```

```{r}
adapt_order15_all_coda <- multi_chain_coda(adapt_order15_all, burn=2000, N_para, p, order)

plot(adapt_order15_all_coda)
gelman.diag(adapt_order15_all_coda)
```


### adapt_all, alpha_star = 0.15

```{r adapt_order15all, cache=TRUE}
adapt_order15_all_alpha15 <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt_all(y=y, x=x, b=b_init[,,i], burn=2000, nsamp=10000, thin=1, order = 15,
                  jump=list(a=a_init[,i], prec = 1/100, positive=pos.est, update.jbw=TRUE),
                  adap=list(alpha_star = 0.15, chol.pivot=TRUE))
```

```{r}
save(adapt_order15_all_alpha15, y, x, b_init, a_init, order, file = "./report/report9/adapt_order15_all_alpha15.RData")
```

```{r}
adapt_order15_all_alpha15_coda <- multi_chain_coda(adapt_order15_all_alpha15, burn=2000, N_para, p, order)

plot(adapt_order15_all_alpha15_coda)
gelman.diag(adapt_order15_all_alpha15_coda)
```


```{r}
adapt_order15_all_alpha15 <- list()
for(i in 1:N_para){
  adapt_order15_all_alpha15[[i]] <- 
    bdregjump_adapt_all(y=y, x=x, b=b_init[,,i], burn=2000, nsamp=10000, thin=1, order = 15,
                  jump=list(a=a_init[,i], prec = 1/100, positive=pos.est, update.jbw=TRUE),
                  adap=list(alpha_star = 0.15, chol.pivot=TRUE), print.process = TRUE)
}

```


```{r}
adapt_order15_all_alpha15_coda <- multi_chain_coda(adapt_order15_all_alpha15, burn=2000, 4, p, order)

plot(adapt_order15_all_alpha15_coda)
gelman.diag(adapt_order15_all_alpha15_coda)
```


# Algorithm 6

### update.jbw = FALSE

```{r adapt_comp_order15_jbw}
adapt_comp_order15_jbw <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt_comp(y=y, x=x, b=b_init[,,i], burn=2000, nsamp=10000, thin=1, order = 15,
                       jump=list(a=a_init[,i], prec = 1/100, positive=pos.est,
                                 persistence=0.68, update.jbw=FALSE))
```

```{r}
save(adapt_comp_order15_jbw, y, x, b_init, a_init, order, file = "./report/report9/adapt_comp_order15_jbw.RData")
```

```{r}
load("./report/report9/adapt_comp_order15_jbw.RData")
adapt_comp_order15_jbw_coda <- multi_chain_coda(adapt_comp_order15_jbw, burn=2000, N_para, p, order)

plot(adapt_comp_order15_jbw_coda)

real_data_plot(adapt_comp_order15_jbw[[1]], x, x.test, y.test, yFn)
real_data_plot(adapt_order15_jbw[[1]], x, x.test, y.test, yFn)

real_data_plot(adapt_comp_order15_jbw[[2]], x, x.test, y.test, yFn)

gelman.diag(adapt_comp_order15_jbw_coda)

adapt_comp_order15_jbw[[1]]$p_accept_corrd[,9900:10000]
adapt_comp_order15_jbw[[1]]$loglambda_adap[,9900:10000]

plot(adapt_comp_order15_jbw[[1]]$loglambda_adap[1,], type = "l")
plot(adapt_comp_order15_jbw[[1]]$p_accept_corrd[1,], type = "l")
```