---
title: "report24"
author: "Haoliang Zheng"
date: "6/1/2021"
output:
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/zhl/Desktop/drdisc")
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = 'center', 
                      fig.width=6, fig.height=7)

library(abind)
library(knitr)
library(latex2exp)
require(magrittr)
require(plyr)
library(tidyverse)
library(coda)
library(doParallel)
library(doMC) 
library(foreach)
library(doRNG)
library(gridExtra)

adapt <- FALSE
bunch <- FALSE
N_para <- 6

registerDoMC(6)
```


```{r source, include=FALSE}
source("./codes/new-codes.R")
source("./codes/test-codes.R")
source("./codes/other-codes.R")

multi_chain_coda_noa <- function(result_multi, burn = 1000, N_para, p, order){
  coda_result <- list()
  matrix_result <- NULL
  for(i in 1:N_para){
    matrix_result <- NULL
    for(j in 1:order){
      for(k in 1:p){
        bijk <- matrix(result_multi[[i]]$b[j,k,], ncol = 1)
        colnames(bijk) <- paste0("b",j,k)
        matrix_result <- cbind(matrix_result, bijk)
      }
    }
    coda_result[[i]] <- mcmc(matrix_result, start = burn+1)
  }
  coda_result_list <- mcmc.list(coda_result)
  
  return(coda_result_list)
}
```

```{r}
bdregjump_adapt_poly_trim_alphanoPG_noshape <- function(y, x=1, b=NULL, nsamp=100, thin=1, burn=100, 
                                      shapes=c(1,1), prec=1, order = 3, trim = 0.5,
                                      jump=list(a=NULL, persistence=0.5, positive=TRUE, 
                                                prec=1, ncand=10, update.jbw=TRUE),
                                      adap=list(mu_adap=NULL, Sigma_adap=NULL,
                                                alpha_star = 0.234, r_adap = 2/3,
                                                chol.pivot=FALSE),
                                      print.process = FALSE, print.i = FALSE){
  
  lpoly <- list(
    #  Vectorize(function(x) return(1/sqrt(2)), "x"), ## k = 0
    function(x) return(sqrt(3/2)*x), ## k = 1
    function(x) return(sqrt(5/8)*(3*x^2 - 1)), ## k = 2
    function(x) return(sqrt(7/8)*(5*x^3 - 3*x)) ## k = 3
  )
  lpoly <- lpoly[1:order]
  get.poly.mat <- function(y) return(sapply(lpoly, function(f) f(y)))
  yFn <- get.poly.mat
  
  n <- length(y)
  if(is.null(dim(x))) x <- matrix(x, nrow=n)
  p <- ncol(x)
  if(is.null(b)) b <- replicate(p, rep(0,order))
  b <- matrix(b, order, p)
  if(length(prec) < p) prec <- rep(prec, p)[1:p]
  shapes.bp <- c(qlogis(shapes[1]/sum(shapes)), sum(shapes))
  
  a <- jump$a
  if(is.null(a)) a <- rep(0, p)
  persistence <- jump$persistence
  if(is.null(persistence)) persistence <- 0.5
  jbw <- 0.16*2*persistence
  positive <- jump$positive
  if(is.null(positive)) positive <- FALSE
  hprec <- jump$prec
  if(is.null(hprec)) hprec <- 1
  ncand <- jump$ncand
  if(is.null(ncand)) ncand <- 10
  update.jbw <- jump$update.jbw
  if(is.null(update.jbw)) update.jbw <- TRUE
  
  loglambda_adap <- log(2.38^2/p)
  
  mu_adap <- adap$mu_adap
  if(is.null(mu_adap)) mu_adap <- matrix(rep(0,p), ncol = 1)
  Sigma_adap <- adap$Sigma_adap
  if(is.null(Sigma_adap)) Sigma_adap <- diag(p)
  alpha_star <- adap$alpha_star
  if(is.null(alpha_star)) alpha_star <- 0.234
  r_adap <- adap$r_adap
  if(is.null(r_adap)) r_adap <- 2/3
  chol.pivot <- adap$chol.pivot
  if(is.null(chol.pivot)) chol.pivot <- FALSE
  
  Poly.obs <- get.poly.mat(y)
  b.store <- array(NA, dim=c(order, p, nsamp))
  a.store <- matrix(NA, p, nsamp)
  az.new.store <- matrix(NA, p, nsamp)
  jbw.store <- rep(NA, nsamp)
  Ntot.store <- rep(NA, nsamp)
  shapes.store <- matrix(NA, 2, nsamp)
  Sigma_adap.store <- array(NA, dim=c(p, p, nsamp))
  loglambda_adap.store <- rep(NA, nsamp)
  sample_i_count.store <- rep(NA, nsamp)
  p_accept.store <- rep(NA, nsamp)
  count.store <- 0
  nacpt <- 0
  nacpt.bp <- 0
  bp.df <- 6
  az.new <- rep(0,p)
  
  diff_prev <- burn_i_count <- sample_i_count <- 0
  
  ## get.miss.reject.x ##
  
  get.miss.reject.x <- function(b, n, x, a, shapes=c(1,1), jbw=0.16, 
                                trim, positive=FALSE){
    n.hits <- 0
    n.miss <- 0
    Poly.miss <- NULL
    Half.miss <- NULL
    w.miss <- NULL
    x.miss <- NULL
    y.miss <- NULL
    
    xa <- c(x %*% a)
    if(positive) xa <- pmax(0, xa)
    
    n.remain <- n
    ix.remain <- 1:n
    while(n.remain > 0){
      z <- 2*rtrunc(n.remain, "beta", a = (1-trim)/2, b = (1+trim)/2,
                    shape1 = shapes[1], shape2 = shapes[2]) - 1
      pm <- matrix(yFn(z), nrow=n.remain)
      hk <- half.kern(z,jbw)
      x.remain <- x[ix.remain,,drop=FALSE]
      xa.remain <- xa[ix.remain]
      w <- rowSums(x.remain * (pm %*% b)) + xa.remain*hk
      u <- (runif(n.remain) < Phi(w))
      n.reject <- sum(!u)
      if(n.reject > 0){
        Poly.miss <- rbind(Poly.miss, pm[!u,])
        Half.miss <- c(Half.miss, hk[!u])
        w.miss <- c(w.miss, w[!u])
        x.miss <- rbind(x.miss, x.remain[!u,,drop=FALSE])
        y.miss <- c(y.miss, z[!u])
      }
      n.remain <- n.reject
      ix.remain <- ix.remain[!u]
      n.miss <- n.miss + n.reject
    }
    return(list(Poly.miss=as.matrix(Poly.miss), Half.miss=Half.miss, 
                w.miss=w.miss, n.miss=n.miss, x.miss=x.miss, y.miss=y.miss))
  }
  
  get.log.likelihood <- function(y, x, Poly.obs, Poly.miss,
                                 y.miss, x.miss,
                                 a, b, jbw){
    
    Half.obs <- half.kern(y, jbw)
    Half.miss <- half.kern(y.miss, jbw)
    
    xa.obs <- c(x %*% a)
    xa.miss <- c(x.miss %*% a)
    if(positive){
      xa.obs <- pmax(0, xa.obs)
      xa.miss <- pmax(0, xa.miss)
    }
    w.obs <- rowSums(x * (Poly.obs %*% b)) + xa.obs * Half.obs
    w.miss <- rowSums(x.miss * (Poly.miss %*% b)) + xa.miss * Half.miss
    
    log.likelihood <- sum(plogis(w.obs, log.p = TRUE)) +
      sum(plogis(w.miss, lower.tail = FALSE, log.p = TRUE))
    return(log.likelihood)
  }
  
  ##
  
  time.stamp.0 <- proc.time()
  for(iter in -(burn-1):(nsamp*thin)){
    
    Half.obs <- half.kern(y, jbw)
    xa.obs <- c(x %*% a)
    if(positive) xa.obs <- pmax(0, xa.obs)
    
    w.obs <- rowSums(x * (Poly.obs %*% b)) + xa.obs * Half.obs
    
    missing.stuff <- get.miss.reject.x(b, n, x, a, shapes, jbw, 
                                       trim, positive)
    n.miss <- missing.stuff$n.miss
    Poly.miss <- missing.stuff$Poly.miss
    Half.miss <- missing.stuff$Half.miss
    w.miss <- missing.stuff$w.miss
    x.miss <- missing.stuff$x.miss
    y.miss <- missing.stuff$y.miss
    
    if(sum(y.miss==-trim) > 0) y.miss[y.miss==-trim] <- (-trim + 1e-10)
    if(sum(y.miss==trim) > 0) y.miss[y.miss==trim] <- (trim - 1e-10)
    
    Ntot <- n + n.miss  
    
    Poly.comb <- rbind(Poly.obs, Poly.miss)
    Half.comb <- c(Half.obs, Half.miss)
    w.comb <- c(w.obs, w.miss)
    x.comb <- rbind(x, x.miss)
    y.comb <- c(y, y.miss)
    
    u.comb <- rep(c(1,0), c(n, n.miss))
    pg.draws <- pmax(1e-12, rpg.devroye(Ntot, h=1, z=w.comb))
    pg.resp <- (u.comb - 0.5)/pg.draws
    pg.residual <- pg.resp - w.comb
    
    ## update b
    for(j in 1:p){
      xPoly.j <- x.comb[,j] * Poly.comb
      pg.residual <- pg.residual + c(xPoly.j %*% b[,j])
      
      Yw <- pg.residual * sqrt(pg.draws)
      Xw <- xPoly.j * sqrt(pg.draws)
      Uw <- chol(crossprod(Xw) + diag(prec[j],order))
      b[,j] <- c(backsolve(Uw, backsolve(Uw, crossprod(Xw,Yw), transpose=TRUE) + rnorm(order)))
      if(any(is.na(b[,j]))) stop("NAs in b")
      pg.residual <- pg.residual - c(xPoly.j %*% b[,j])
    }
    
    ## update a
    xa <- c(x.comb %*% a)
    if(positive) xa <- pmax(0, xa)
    
    pg.residual <- pg.residual + xa * Half.comb
    
    Sigma_chol <- exp(loglambda_adap/2) * chol(Sigma_adap + diag(1e-10, p), pivot = chol.pivot)
    if(chol.pivot == TRUE){
      var_order <- attr(Sigma_chol, "pivot")
      az.new[var_order] <- crossprod(Sigma_chol, rnorm(p))
    } else{
      az.new <- crossprod(Sigma_chol, rnorm(p))
    }
    
    a.new <- a + az.new
    xa.new <- c(x.comb %*% a.new)
    if(positive) xa.new <- pmax(0, xa.new)
    
    loglike.new <- get.log.likelihood(y = y, x = x,
                                      Poly.obs = Poly.obs, Poly.miss = Poly.miss,
                                      y.miss = y.miss, x.miss = x.miss,
                                      a = a.new, b = b, jbw = jbw)
    loglike <- get.log.likelihood(y = y, x = x,
                                  Poly.obs = Poly.obs, Poly.miss = Poly.miss,
                                  y.miss = y.miss, x.miss = x.miss,
                                  a = a, b = b, jbw = jbw)
    
    log.hastings.ratio <- ( (loglike.new - loglike) +
                              sum(dnorm(a.new,0,sqrt(1/hprec),log=TRUE)
                                  - dnorm(a,0,sqrt(1/hprec),log=TRUE)) )
    
    if(log(runif(1)) < log.hastings.ratio){
      a <- a.new
      xa <- xa.new
      nacpt <- nacpt+1
    }
    p_accept <- min(1, exp(log.hastings.ratio))
    
    if(iter <= 0) {
      diff_curr <- p_accept - alpha_star
      burn_i_count <- burn_i_count + ((diff_prev * diff_curr) <= 0)
      gamma_adap <- min(0.5, 1/(burn_i_count^r_adap))
      diff_prev <- diff_curr
      
      if(print.i) print(burn_i_count)
    }
    else {
      diff_curr <- p_accept - alpha_star
      sample_i_count <- sample_i_count + ((diff_prev * diff_curr) <= 0)
      gamma_adap <- min(0.5, 1/(sample_i_count^r_adap))
      diff_prev <- diff_curr
      
      if(print.i) print(sample_i_count)
    }
    
    loglambda_adap <- loglambda_adap + gamma_adap * (p_accept - alpha_star)
    a_mu_diff <- a - mu_adap
    mu_adap <- mu_adap + gamma_adap * a_mu_diff
    Sigma_adap <- Sigma_adap + gamma_adap*(tcrossprod(a_mu_diff, a_mu_diff) - Sigma_adap)
    
    pg.residual <- pg.residual - xa * Half.comb
    
    ## update jbw
    if(update.jbw){
      persistence.cand <- rprior.persistence(ncand)
      jbw.cand <- 2*0.16*persistence.cand
      Half.comb.cand <- sapply(jbw.cand, function(bw) half.kern(y.comb, bw))
      res.cand <- pg.residual + xa * Half.comb - xa * Half.comb.cand
      lp0 <- dnorm(pg.residual,0,sqrt(1/pg.draws),log=TRUE)
      lp.cand <- c(apply(res.cand, 
                         2, 
                         function(res) sum(dnorm(res,0,sqrt(1/pg.draws),log=TRUE) - lp0)), 
                   0)
      cand.draw <- sample(ncand+1,1,prob=exp(lp.cand - logsum(lp.cand)))
      if(cand.draw < ncand+1) jbw <- jbw.cand[cand.draw]
    }    
  
    
    if(print.process) print(iter)
    
    if(iter > 0 & (iter %% thin == 0)){
      count.store <- count.store + 1
      b.store[,,count.store] <- b
      a.store[,count.store] <- a
      az.new.store[,count.store] <- az.new
      jbw.store[count.store] <- jbw
      Ntot.store[count.store] <- Ntot
      shapes.store[,count.store] <- shapes
      Sigma_adap.store[,,count.store] <- Sigma_adap
      loglambda_adap.store[count.store] <- loglambda_adap
      sample_i_count.store[count.store] <- sample_i_count
      p_accept.store[count.store] <- p_accept
    }
  }
  run.time <- proc.time() - time.stamp.0
  return(list(b=b.store, a=a.store, az.new = az.new.store, jbw=jbw.store, Ntot=Ntot.store,
              Sigma_adap = Sigma_adap.store, loglambda_adap = loglambda_adap.store,
              shapes=shapes.store, sample_i_count = sample_i_count.store,
              p_accept = p_accept.store,
              runtime=run.time, 
              acpt=c(a=nacpt)/(burn+nsamp*thin))
  )
}
```


```{r}
bdregjump_adapt_poly_trim_alphanoPG_shapeadapt <- function(y, x=1, b=NULL, nsamp=100, thin=1, burn=100, 
                                      shapes=c(1,1), prec=1, order = 3, trim = 0.5,
                                      jump=list(a=NULL, persistence=0.5, positive=TRUE, 
                                                prec=1, ncand=10, update.jbw=TRUE),
                                      adap=list(mu_adap=NULL, Sigma_adap=NULL,
                                                alpha_star = 0.234, r_adap = 2/3,
                                                chol.pivot=FALSE),
                                      print.process = FALSE, print.i = FALSE){
  
  lpoly <- list(
    #  Vectorize(function(x) return(1/sqrt(2)), "x"), ## k = 0
    function(x) return(sqrt(3/2)*x), ## k = 1
    function(x) return(sqrt(5/8)*(3*x^2 - 1)), ## k = 2
    function(x) return(sqrt(7/8)*(5*x^3 - 3*x)) ## k = 3
  )
  lpoly <- lpoly[1:order]
  get.poly.mat <- function(y) return(sapply(lpoly, function(f) f(y)))
  yFn <- get.poly.mat
  
  n <- length(y)
  if(is.null(dim(x))) x <- matrix(x, nrow=n)
  p <- ncol(x)
  if(is.null(b)) b <- replicate(p, rep(0,order))
  b <- matrix(b, order, p)
  if(length(prec) < p) prec <- rep(prec, p)[1:p]
  shapes_log <- log(shapes)
  
  a <- jump$a
  if(is.null(a)) a <- rep(0, p)
  persistence <- jump$persistence
  if(is.null(persistence)) persistence <- 0.5
  jbw <- 0.16*2*persistence
  positive <- jump$positive
  if(is.null(positive)) positive <- FALSE
  hprec <- jump$prec
  if(is.null(hprec)) hprec <- 1
  ncand <- jump$ncand
  if(is.null(ncand)) ncand <- 10
  update.jbw <- jump$update.jbw
  if(is.null(update.jbw)) update.jbw <- TRUE
  
  loglambda_adap <- log(2.38^2/p)
  
  mu_adap <- adap$mu_adap
  if(is.null(mu_adap)) mu_adap <- matrix(rep(0,p), ncol = 1)
  Sigma_adap <- adap$Sigma_adap
  if(is.null(Sigma_adap)) Sigma_adap <- diag(p)
  alpha_star <- adap$alpha_star
  if(is.null(alpha_star)) alpha_star <- 0.234
  r_adap <- adap$r_adap
  if(is.null(r_adap)) r_adap <- 2/3
  chol.pivot <- adap$chol.pivot
  if(is.null(chol.pivot)) chol.pivot <- FALSE
  
  Poly.obs <- get.poly.mat(y)
  b.store <- array(NA, dim=c(order, p, nsamp))
  a.store <- matrix(NA, p, nsamp)
  az.new.store <- matrix(NA, p, nsamp)
  jbw.store <- rep(NA, nsamp)
  Ntot.store <- rep(NA, nsamp)
  shapes.store <- matrix(NA, 2, nsamp)
  Sigma_adap.store <- array(NA, dim=c(p, p, nsamp))
  loglambda_adap.store <- rep(NA, nsamp)
  sample_i_count.store <- rep(NA, nsamp)
  p_accept.store <- rep(NA, nsamp)
  count.store <- 0
  nacpt <- 0
  nacpt.bp <- 0
  bp.df <- 6
  az.new <- rep(0,p)
  
  diff_prev <- burn_i_count <- sample_i_count <- 0
  
  beta.loglik <- function(shapes, yy, trim = 1){
  if(trim == 1){
    result <- sum(dbeta(yy, shapes[1], shapes[2], log=TRUE))
  } else{
    result <- sum(log(dtrunc(yy, "beta", a = (1-trim)/2, b = (1+trim)/2,
                             shape1 = shapes[1], shape2 = shapes[2])))
  }
  return(result)
}
  
  ## get.miss.reject.x ##
  
  get.miss.reject.x <- function(b, n, x, a, shapes=c(1,1), jbw=0.16, 
                                trim, positive=FALSE){
    n.hits <- 0
    n.miss <- 0
    Poly.miss <- NULL
    Half.miss <- NULL
    w.miss <- NULL
    x.miss <- NULL
    y.miss <- NULL
    
    xa <- c(x %*% a)
    if(positive) xa <- pmax(0, xa)
    
    n.remain <- n
    ix.remain <- 1:n
    while(n.remain > 0){
      z <- 2*rtrunc(n.remain, "beta", a = (1-trim)/2, b = (1+trim)/2,
                    shape1 = shapes[1], shape2 = shapes[2]) - 1
      pm <- matrix(yFn(z), nrow=n.remain)
      hk <- half.kern(z,jbw)
      x.remain <- x[ix.remain,,drop=FALSE]
      xa.remain <- xa[ix.remain]
      w <- rowSums(x.remain * (pm %*% b)) + xa.remain*hk
      u <- (runif(n.remain) < Phi(w))
      n.reject <- sum(!u)
      if(n.reject > 0){
        Poly.miss <- rbind(Poly.miss, pm[!u,])
        Half.miss <- c(Half.miss, hk[!u])
        w.miss <- c(w.miss, w[!u])
        x.miss <- rbind(x.miss, x.remain[!u,,drop=FALSE])
        y.miss <- c(y.miss, z[!u])
      }
      n.remain <- n.reject
      ix.remain <- ix.remain[!u]
      n.miss <- n.miss + n.reject
    }
    return(list(Poly.miss=as.matrix(Poly.miss), Half.miss=Half.miss, 
                w.miss=w.miss, n.miss=n.miss, x.miss=x.miss, y.miss=y.miss))
  }
  
  get.log.likelihood <- function(y, x, Poly.obs, Poly.miss,
                                 y.miss, x.miss,
                                 a, b, jbw){
    
    Half.obs <- half.kern(y, jbw)
    Half.miss <- half.kern(y.miss, jbw)
    
    xa.obs <- c(x %*% a)
    xa.miss <- c(x.miss %*% a)
    if(positive){
      xa.obs <- pmax(0, xa.obs)
      xa.miss <- pmax(0, xa.miss)
    }
    w.obs <- rowSums(x * (Poly.obs %*% b)) + xa.obs * Half.obs
    w.miss <- rowSums(x.miss * (Poly.miss %*% b)) + xa.miss * Half.miss
    
    log.likelihood <- sum(plogis(w.obs, log.p = TRUE)) +
      sum(plogis(w.miss, lower.tail = FALSE, log.p = TRUE))
    return(log.likelihood)
  }
  
  ##
  
  time.stamp.0 <- proc.time()
  for(iter in -(burn-1):(nsamp*thin)){
    
    Half.obs <- half.kern(y, jbw)
    xa.obs <- c(x %*% a)
    if(positive) xa.obs <- pmax(0, xa.obs)
    
    w.obs <- rowSums(x * (Poly.obs %*% b)) + xa.obs * Half.obs
    
    missing.stuff <- get.miss.reject.x(b, n, x, a, shapes, jbw, 
                                       trim, positive)
    n.miss <- missing.stuff$n.miss
    Poly.miss <- missing.stuff$Poly.miss
    Half.miss <- missing.stuff$Half.miss
    w.miss <- missing.stuff$w.miss
    x.miss <- missing.stuff$x.miss
    y.miss <- missing.stuff$y.miss
    
    if(sum(y.miss==-trim) > 0) y.miss[y.miss==-trim] <- (-trim + 1e-10)
    if(sum(y.miss==trim) > 0) y.miss[y.miss==trim] <- (trim - 1e-10)
    
    Ntot <- n + n.miss  
    
    Poly.comb <- rbind(Poly.obs, Poly.miss)
    Half.comb <- c(Half.obs, Half.miss)
    w.comb <- c(w.obs, w.miss)
    x.comb <- rbind(x, x.miss)
    y.comb <- c(y, y.miss)
    
    u.comb <- rep(c(1,0), c(n, n.miss))
    pg.draws <- pmax(1e-12, rpg.devroye(Ntot, h=1, z=w.comb))
    pg.resp <- (u.comb - 0.5)/pg.draws
    pg.residual <- pg.resp - w.comb
    
    ## update b
    for(j in 1:p){
      xPoly.j <- x.comb[,j] * Poly.comb
      pg.residual <- pg.residual + c(xPoly.j %*% b[,j])
      
      Yw <- pg.residual * sqrt(pg.draws)
      Xw <- xPoly.j * sqrt(pg.draws)
      Uw <- chol(crossprod(Xw) + diag(prec[j],order))
      b[,j] <- c(backsolve(Uw, backsolve(Uw, crossprod(Xw,Yw), transpose=TRUE) + rnorm(order)))
      if(any(is.na(b[,j]))) stop("NAs in b")
      pg.residual <- pg.residual - c(xPoly.j %*% b[,j])
    }
    
    ## update a
    xa <- c(x.comb %*% a)
    if(positive) xa <- pmax(0, xa)
    
    pg.residual <- pg.residual + xa * Half.comb
    
    Sigma_chol <- exp(loglambda_adap/2) * chol(Sigma_adap + diag(1e-10, p), pivot = chol.pivot)
    if(chol.pivot == TRUE){
      var_order <- attr(Sigma_chol, "pivot")
      az.new[var_order] <- crossprod(Sigma_chol, rnorm(p))
    } else{
      az.new <- crossprod(Sigma_chol, rnorm(p))
    }
    
    a.new <- a + az.new
    xa.new <- c(x.comb %*% a.new)
    if(positive) xa.new <- pmax(0, xa.new)
    
    loglike.new <- get.log.likelihood(y = y, x = x,
                                      Poly.obs = Poly.obs, Poly.miss = Poly.miss,
                                      y.miss = y.miss, x.miss = x.miss,
                                      a = a.new, b = b, jbw = jbw)
    loglike <- get.log.likelihood(y = y, x = x,
                                  Poly.obs = Poly.obs, Poly.miss = Poly.miss,
                                  y.miss = y.miss, x.miss = x.miss,
                                  a = a, b = b, jbw = jbw)
    
    log.hastings.ratio <- ( (loglike.new - loglike) +
                              sum(dnorm(a.new,0,sqrt(1/hprec),log=TRUE)
                                  - dnorm(a,0,sqrt(1/hprec),log=TRUE)) )
    
    if(log(runif(1)) < log.hastings.ratio){
      a <- a.new
      xa <- xa.new
      nacpt <- nacpt+1
    }
    p_accept <- min(1, exp(log.hastings.ratio))
    
    if(iter <= 0) {
      diff_curr <- p_accept - alpha_star
      burn_i_count <- burn_i_count + ((diff_prev * diff_curr) <= 0)
      gamma_adap <- min(0.5, 1/(burn_i_count^r_adap))
      diff_prev <- diff_curr
      
      if(print.i) print(burn_i_count)
    }
    else {
      diff_curr <- p_accept - alpha_star
      sample_i_count <- sample_i_count + ((diff_prev * diff_curr) <= 0)
      gamma_adap <- min(0.5, 1/(sample_i_count^r_adap))
      diff_prev <- diff_curr
      
      if(print.i) print(sample_i_count)
    }
    
    loglambda_adap <- loglambda_adap + gamma_adap * (p_accept - alpha_star)
    a_mu_diff <- a - mu_adap
    mu_adap <- mu_adap + gamma_adap * a_mu_diff
    Sigma_adap <- Sigma_adap + gamma_adap*(tcrossprod(a_mu_diff, a_mu_diff) - Sigma_adap)
    
    pg.residual <- pg.residual - xa * Half.comb
    
    ## update jbw
    if(update.jbw){
      persistence.cand <- rprior.persistence(ncand)
      jbw.cand <- 2*0.16*persistence.cand
      Half.comb.cand <- sapply(jbw.cand, function(bw) half.kern(y.comb, bw))
      res.cand <- pg.residual + xa * Half.comb - xa * Half.comb.cand
      lp0 <- dnorm(pg.residual,0,sqrt(1/pg.draws),log=TRUE)
      lp.cand <- c(apply(res.cand, 
                         2, 
                         function(res) sum(dnorm(res,0,sqrt(1/pg.draws),log=TRUE) - lp0)), 
                   0)
      cand.draw <- sample(ncand+1,1,prob=exp(lp.cand - logsum(lp.cand)))
      if(cand.draw < ncand+1) jbw <- jbw.cand[cand.draw]
    }    
    
    ## update beta shapes
    beta.y <- (1+y.comb)/2
    
    shapes_log_new1 <- rnorm(1, shapes_log[1], 0.03)
    shapes_log_new2 <- rnorm(1, shapes_log[2], 0.03)
    
    shapes_log_new <- c(shapes_log_new1, shapes_log_new2)
    shapes_new <- exp(shapes_log_new)
  
    log_has <- beta.loglik(shapes_new, beta.y, trim) + sum(shapes_log_new) -
      beta.loglik(shapes, beta.y, trim) - sum(shapes_log)
    
    if(log(runif(1)) < log_has){
      shapes <- shapes_new
      shapes_log <- shapes_log_new
      nacpt.bp <- nacpt.bp+1
      }
    
    if(print.process) print(iter)
    
    if(iter > 0 & (iter %% thin == 0)){
      count.store <- count.store + 1
      b.store[,,count.store] <- b
      a.store[,count.store] <- a
      az.new.store[,count.store] <- az.new
      jbw.store[count.store] <- jbw
      Ntot.store[count.store] <- Ntot
      shapes.store[,count.store] <- shapes
      Sigma_adap.store[,,count.store] <- Sigma_adap
      loglambda_adap.store[count.store] <- loglambda_adap
      sample_i_count.store[count.store] <- sample_i_count
      p_accept.store[count.store] <- p_accept
    }
  }
  run.time <- proc.time() - time.stamp.0
  return(list(b=b.store, a=a.store, az.new = az.new.store, jbw=jbw.store, Ntot=Ntot.store,
              Sigma_adap = Sigma_adap.store, loglambda_adap = loglambda_adap.store,
              shapes=shapes.store, sample_i_count = sample_i_count.store,
              p_accept = p_accept.store,
              runtime=run.time, 
              acpt=c(a=nacpt, store=nacpt.bp)/(burn+nsamp*thin))
  )
}

```


# simulated data, order = 2

```{r}
N_para <- 6
simulate <- TRUE
## Density regression with jump
if(simulate){
  set.seed(123)
  p <- 2
  n.obs <- 6e4
  b0x <- cbind(b0, threshold(rt(order, df=6),1))
  while(ncol(b0x) < p) b0x <- cbind(b0x, 0)
  a0 <- c(1, 4, rep(0,p-2))
  shapes0 <- c(4,1)
  pers0 <- 1/2
  jbw0 <- 0.16*2*pers0
  pos.synth <- TRUE
  pos.est <- TRUE
  
  x.obs <- cbind(1, matrix(rnorm(n.obs*(p-1)), n.obs, p-1))
  y.obs <- simulate.fx(n.obs, b0x, x.obs, a0, shapes0, jbw0, positive=pos.synth)
}

N_para <- 6
set.seed(123)
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd = 3), order, p))
a_init <- replicate(N_para, rnorm(n = p, sd = 3))
```

```{r}
hist(y.obs)
```


# no trimming

```{r}
set.seed(123)
order <- 2
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=1), order, p))
a_init <- replicate(N_para, rnorm(n = p, sd = 1.5))
```

```{r ,eval=FALSE}
sim_notrim_order2 <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt_poly_trim_alphanoPG(y=y.obs, x=x.obs,
                                      b=b_init[,,i], burn=15000, nsamp=10000,
                                      thin=1, trim = 1, order = 2,
                                      jump=list(a=a_init[,i], prec = 1, positive=pos.est,
                                                persistence=0.5, update.jbw=TRUE))
```

```{r}
load("./report/report24/sim_notrim_order2.RData")
```

```{r r1, cache=TRUE}
sim_notrim_order2_coda <- multi_chain_coda(sim_notrim_order2,
                                           burn = 15000, N_para, p, order = 2)
```


```{r}
get.result.bdregjump(sim_notrim_order2[[1]], x.obs, y.obs, b0x, a0)
```


# trimming = 0.5

```{r}
trim05_ind <- (abs(y.obs) < 0.5)
sim_data_trim05_y <- y.obs[trim05_ind]
sim_data_trim05_x <- x.obs[trim05_ind,]
```

```{r}
hist(sim_data_trim05_y)
```


```{r ,eval=FALSE}
sim_trim05_order2 <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt_poly_trim_alphanoPG(y=sim_data_trim05_y, x=sim_data_trim05_x,
                                      b=b_init[,,i], burn=15000, nsamp=10000,
                                      thin=1, trim = 0.5, order = 2,
                                      jump=list(a=a_init[,i], prec = 1, positive=pos.est,
                                                persistence=0.5, update.jbw=TRUE))
```


```{r}
i <- 1
sim_trim05_order2_i1 <- bdregjump_adapt_poly_trim_alphanoPG_noshape(y=sim_data_trim05_y, x=sim_data_trim05_x,b=b_init[,,i], burn=15000, nsamp=10000,thin=1,shapes = shapes0, trim = 0.5,
order = 2,jump=list(a=a_init[,i], prec = 1, positive=pos.est,persistence=0.5, update.jbw=TRUE),
print.process = TRUE)
```

```{r}
save(sim_trim05_order2_i1, file = "./report/report24/sim_trim05_order2_i1.RData")
```


```{r}
i <- 1
sim_trim05_order2_i1_shapeadapt22 <- bdregjump_adapt_poly_trim_alphanoPG_shapeadapt(y=sim_data_trim05_y, x=sim_data_trim05_x,b=b_init[,,i], burn=15000, nsamp=10000,thin=1, trim = 0.5,
order = 2,jump=list(a=a_init[,i], prec = 1, positive=pos.est,persistence=0.5, update.jbw=TRUE),
print.process = TRUE)
```

```{r}
save(sim_trim05_order2_i1_shapeadapt22, file = "./report/report24/sim_trim05_order2_i1_shapeadapt22.RData")
```

```{r}
set.seed(123)
get.result.bdregjump(sim_trim05_order2_i1_shapeadapt22, 
                     sim_data_trim05_x, sim_data_trim05_y, b0x, a0,
                     trim=0.5)
```


```{r}
load("./report/report24/sim_trim05_order2.RData")
```

```{r r2, cache=TRUE}
sim_trim05_order2_coda <- multi_chain_coda(sim_trim05_order2,
                                           burn = 15000, N_para, p, order = 2)
```


```{r}
set.seed(123)
get.result.bdregjump(sim_trim05_order2[[1]], 
                     sim_data_trim05_x, sim_data_trim05_y, b0x, a0,
                     trim=0.5)
```


# drop

```{r}
get.drop <- function(fit.x, x.obs, y.obs, b0x, a0,
                     trim = 1, thin_index=NULL){
  drop.res <- NULL
  
  y.grid <- seq(-trim, trim, .01)
  if(is.null(thin_index)){
    b.est <- fit.x$b
    a.est <- fit.x$a
    shapes.est <- fit.x$shapes
    jbw.est <- fit.x$jbw
  }else{
    b.est <- fit.x$b[,,thin_index]
    a.est <- fit.x$a[,thin_index]
    shapes.est <- fit.x$shapes[,thin_index]
    jbw.est <- fit.x$jbw[thin_index]
  }
  
  p <- dim(fit.x$b)[2]
  
  xnew <- rep(1, 81)
  for(i in 1:(p-1)) xnew <- cbind(xnew, seq(-2,2,0.05))
  nnew <- nrow(xnew)
  xb0 <- tcrossprod(xnew, b0x)
  xa0 <- c(xnew %*% a0)
  if(pos.synth) xa0 <- pmax(0, xa0)
  
  nsamp <- ncol(a.est)
  drop_pos <- trim/0.01
  for(cl in 1:81){
    xb <- apply(b.est, 3, function(b) tcrossprod(xnew[cl,,drop=FALSE], b))
    xa <- c(xnew[cl,,drop=FALSE] %*% a.est)
    if(pos.est) xa <- pmax(xa, 0)
    fx <- sapply(1:nsamp, function(s) get.f(b=xb[,s],a=xa[s],sh=shapes.est[,s],jbw=jbw.est[s],
                                            trim=trim, post=FALSE))
    
    dropx <- 1-fx[drop_pos,]/fx[drop_pos+1,]
    drop.res <- c(drop.res, median(dropx))
  }
  
  return(drop.res)
}
```

```{r eval=FALSE}
drop_notrim_order2 <- get.drop(sim_notrim_order2[[1]], 
                               x.obs, y.obs, b0x, a0)
```


```{r dro, cache=TRUE}
load("./report/report24/drop_notrim_order2.RData")

drop_trim05_order2 <- get.drop(sim_trim05_order2[[1]], 
                               sim_data_trim05_x, sim_data_trim05_y, b0x, a0,
                               trim=0.5)

plot(drop_notrim_order2, drop_trim05_order2)
abline(0, 1, col = "red")
```

# simulated data, pri, order = 2

```{r}
trim <- 0.5
y.grid <- seq(-trim, trim, 0.01)
f0 <- get.f0(y.grid)
h2.loss <- function(b){
  f.nc <- integrate(fFn, -trim, trim, beta=b)$value
  return(integrate(function(y) (sqrt(fFn(y, beta=b)/f.nc) - sqrt(get.f0(y)))^2,-trim,trim)$value)
}
best.fit <- optim(rep(0,order), h2.loss, method="BFGS")
b0 <- best.fit$par
f0b <- get.f(b0)
```


```{r}
N_para <- 6
simulate <- TRUE
## Density regression with jump
if(simulate){
  set.seed(123)
  p <- 2
  n.obs <- 2e4
  b0x <- cbind(b0, threshold(rt(order, df=6),1))
  while(ncol(b0x) < p) b0x <- cbind(b0x, 0)
  a0 <- c(2, 5, rep(0,p-2))
  shapes0 <- c(2,1)
  pers0 <- 1/2
  jbw0 <- 0.16*2*pers0
  pos.synth <- TRUE
  pos.est <- TRUE
  
  x.obs <- cbind(1, matrix(rnorm(n.obs*(p-1)), n.obs, p-1))
  y.obs_trim <- simulate.fx(n.obs, b0x, x.obs, a0, shapes0, jbw0,
                       trim = 0.5, positive=pos.synth)
}

N_para <- 6
set.seed(123)
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd = 3), order, p))
a_init <- replicate(N_para, rnorm(n = p, sd = 3))
```

```{r}
hist(y.obs_trim)
```


```{r ,eval=FALSE}
sim_trim05_pri_order2 <- bdregjump_adapt_poly_trim_alphanoPG(y=y.obs_trim, x=x.obs,
                                      b=b_init[,,1], burn=15000, nsamp=10000,
                                      thin=1, trim = 0.5, order = 2,
                                      jump=list(a=a_init[,1], prec = 1, positive=pos.est,
                                                persistence=0.5, update.jbw=TRUE))
```

```{r}
load("./report/report24/sim_trim05_pri_order2.RData")
```


```{r}
get.result.bdregjump(sim_trim05_pri_order2, 
                     x.obs, y.obs_trim, b0x, a0,
                     trim=0.5, post = FALSE)
```


