---
title: "report22"
author: "Haoliang Zheng"
date: "5/19/2021"
output:
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/zhl/Desktop/drdisc")
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = 'center', 
                      fig.width=6, fig.height=7)

library(abind)
library(knitr)
library(latex2exp)
require(magrittr)
require(plyr)
library(tidyverse)
library(coda)
library(doParallel)
library(doMC) 
library(foreach)
library(doRNG)

adapt <- FALSE
bunch <- FALSE
N_para <- 6

registerDoMC(6)
```


```{r source, include=FALSE}
source("./codes/new-codes.R")
source("./codes/test-codes.R")
source("./codes/other-codes.R")

multi_chain_coda_noa <- function(result_multi, burn = 1000, N_para, p, order){
  coda_result <- list()
  matrix_result <- NULL
  for(i in 1:N_para){
    matrix_result <- NULL
    for(j in 1:order){
      for(k in 1:p){
        bijk <- matrix(result_multi[[i]]$b[j,k,], ncol = 1)
        colnames(bijk) <- paste0("b",j,k)
        matrix_result <- cbind(matrix_result, bijk)
      }
    }
    coda_result[[i]] <- mcmc(matrix_result, start = burn+1)
  }
  coda_result_list <- mcmc.list(coda_result)
  
  return(coda_result_list)
}
```

# data

```{r}
vote <- read.csv("./codes/vote_data.csv")
str(vote)
vote <- subset(vote, abs(from_requirement_threshold) < 0.5)
bunch <- FALSE
pos.est <- TRUE
N_para <- 6
p <- 6
```


```{r}
get.trim.data <- function(trim){
  vote <- subset(vote, abs(from_requirement_threshold) < trim/2)
  preds <- model.matrix(~ #major.requirement 
                        + ISS.against.recommendation 
                      #+ shares.oustanding.base 
                      #+ special.meeting 
                      + analyst.coverage 
                      #+ institutional.ownership 
                      + past.stock.return 
                      + q 
                      + firm.size, 
                      data = vote)[,-1]
  preds.all <- scale(preds)
  x <- cbind(1, preds.all)
  dimnames(x)[[2]][1] <- "Intercept"
  x.names <- dimnames(x)[[2]]
  y <- 2*vote[,"from_requirement_threshold"]
  return(list(x=x, y=y))
}

get.result.CI <- function(result_trim07_order2, N_para = 6, p = 6){
  result_CI_t7o2 <- data.frame()
  for(i in 1:N_para){
    one_set_r <- apply(result_trim07_order2[[i]]$a, 1, function(x) quantile(x, c(0.025, 0.975)))
    for(j in 1:p){
      result_CI_t7o2 <- rbind(result_CI_t7o2,
                              data.frame(lower = one_set_r[1,j],
                                         upper = one_set_r[2,j],
                                         variable = paste0("a", j),
                                         setting = as.character(i)))
      }
    }
  rownames(result_CI_t7o2) <- NULL
  return(result_CI_t7o2)
}
```

# order = 2

## trimming = 0.5

```{r}
set.seed(123)
order <- 2
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=1), order, p))
a_init <- replicate(N_para, rnorm(n = p, sd = 1.5))

data_trim05 <- get.trim.data(0.5)
```

```{r ,eval=FALSE}
result_trim05_order2 <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt_poly_trim_alphanoPG(y=data_trim05$y, x=data_trim05$x, b=b_init[,,i],
                            burn=15000, nsamp=25000, thin=1, trim = 0.5, order = 2,
                            jump=list(a=a_init[,i], prec = 1, positive=pos.est,
                               persistence=0.8, update.jbw=TRUE))
```


```{r}
load("./report/report22/result_trim05_order2.RData")
result_CI_t5o2 <- get.result.CI(result_trim05_order2)
```

```{r ,eval=FALSE}
result_trim05_order2_coda <- multi_chain_coda(result_trim05_order2,
                                              burn = 15000, N_para, p, order = 2)
plot(result_trim05_order2_coda)
gelman.diag(result_trim05_order2_coda)
summary(result_trim05_order2_coda)
```

```{r ,eval=FALSE}
ggplot(result_CI_t5o2, aes(x = variable, colour = setting)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2)
```


## trimming = 0.6

```{r}
set.seed(123)
order <- 2
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=1), order, p))
a_init <- replicate(N_para, rnorm(n = p, sd = 1.5))

data_trim06 <- get.trim.data(0.6)
```

```{r ,eval=FALSE}
result_trim06_order2 <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt_poly_trim_alphanoPG(y=data_trim06$y, x=data_trim06$x, b=b_init[,,i],
                            burn=15000, nsamp=25000, thin=1, trim = 0.6, order = 2,
                            jump=list(a=a_init[,i], prec = 1, positive=pos.est,
                               persistence=0.8, update.jbw=TRUE))
```


```{r}
load("./report/report22/result_trim06_order2.RData")
result_CI_t6o2 <- get.result.CI(result_trim06_order2)
```

```{r ,eval=FALSE}
result_trim06_order2_coda <- multi_chain_coda(result_trim06_order2,
                                              burn = 15000, N_para, p, order = 2)
plot(result_trim06_order2_coda)
gelman.diag(result_trim06_order2_coda)
summary(result_trim06_order2_coda)
```

```{r ,eval=FALSE}
ggplot(result_CI_t6o2, aes(x = variable, colour = setting)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2)
```

## trimming = 0.7

```{r}
set.seed(123)
order <- 2
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=1), order, p))
a_init <- replicate(N_para, rnorm(n = p, sd = 1.5))

data_trim07 <- get.trim.data(0.7)
```

```{r ,eval=FALSE}
result_trim07_order2 <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt_poly_trim_alphanoPG(y=data_trim07$y, x=data_trim07$x, b=b_init[,,i],
                            burn=15000, nsamp=25000, thin=1, trim = 0.7, order = 2,
                            jump=list(a=a_init[,i], prec = 1, positive=pos.est,
                               persistence=0.8, update.jbw=TRUE))
```


```{r}
load("./report/report22/result_trim07_order2.RData")
result_CI_t7o2 <- get.result.CI(result_trim07_order2)
```

```{r ,eval=FALSE}
result_trim07_order2_coda <- multi_chain_coda(result_trim07_order2,
                                              burn = 15000, N_para, p, order = 2)
plot(result_trim07_order2_coda)
gelman.diag(result_trim07_order2_coda)
summary(result_trim07_order2_coda)
```


```{r ,eval=FALSE}
ggplot(result_CI_t7o2, aes(x = variable, colour = setting)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2)
```


# order = 3

## trimming = 0.5

```{r}
set.seed(123)
order <- 2
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=1), order, p))
a_init <- replicate(N_para, rnorm(n = p, sd = 1.5))

data_trim05 <- get.trim.data(0.5)
```

```{r ,eval=FALSE}
result_trim05_order3 <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt_poly_trim_alphanoPG(y=data_trim05$y, x=data_trim05$x, b=b_init[,,i],
                            burn=15000, nsamp=25000, thin=1, trim = 0.5, order = 3,
                            jump=list(a=a_init[,i], prec = 1, positive=pos.est,
                               persistence=0.8, update.jbw=TRUE))
```


```{r}
load("./report/report22/result_trim05_order3.RData")
result_CI_t5o3 <- get.result.CI(result_trim05_order3)
```

```{r ,eval=FALSE}
result_trim05_order3_coda <- multi_chain_coda(result_trim05_order3,
                                              burn = 15000, N_para, p, order = 3)
plot(result_trim05_order3_coda)
gelman.diag(result_trim05_order3_coda)
summary(result_trim05_order3_coda)
```

```{r ,eval=FALSE}
ggplot(result_CI_t5o3, aes(x = variable, colour = setting)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2)
```

## trimming = 0.6

```{r}
set.seed(123)
order <- 2
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=1), order, p))
a_init <- replicate(N_para, rnorm(n = p, sd = 1.5))

data_trim06 <- get.trim.data(0.6)
```

```{r ,eval=FALSE}
result_trim06_order3 <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt_poly_trim_alphanoPG(y=data_trim06$y, x=data_trim06$x, b=b_init[,,i],
                            burn=15000, nsamp=25000, thin=1, trim = 0.6, order = 3,
                            jump=list(a=a_init[,i], prec = 1, positive=pos.est,
                               persistence=0.8, update.jbw=TRUE))
```


```{r}
load("./report/report22/result_trim06_order3.RData")
result_CI_t6o3 <- get.result.CI(result_trim06_order3)
```

```{r}
result_trim06_order3_coda <- multi_chain_coda(result_trim06_order3,
                                              burn = 15000, N_para, p, order = 3)
plot(result_trim06_order3_coda)
gelman.diag(result_trim06_order3_coda)
```

```{r ,eval=FALSE}
ggplot(result_CI_t6o3, aes(x = variable, colour = setting)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2)
```

## trimming = 0.7

```{r}
set.seed(123)
order <- 2
b_init <- replicate(N_para, matrix(rnorm(n = order*p, sd=1), order, p))
a_init <- replicate(N_para, rnorm(n = p, sd = 1.5))

data_trim07 <- get.trim.data(0.7)
```

```{r ,eval=FALSE}
result_trim07_order3 <- foreach(i = 1:N_para) %dorng%
  bdregjump_adapt_poly_trim_alphanoPG(y=data_trim07$y, x=data_trim07$x, b=b_init[,,i],
                            burn=15000, nsamp=25000, thin=1, trim = 0.7, order = 3,
                            jump=list(a=a_init[,i], prec = 1, positive=pos.est,
                               persistence=0.8, update.jbw=TRUE))
```


```{r}
load("./report/report22/result_trim07_order3.RData")
result_CI_t7o3 <- get.result.CI(result_trim07_order3)
```

```{r ,eval=FALSE}
result_trim07_order3_coda <- multi_chain_coda(result_trim07_order3,
                                              burn = 15000, N_para, p, order = 3)
plot(result_trim07_order3_coda)
gelman.diag(result_trim07_order3_coda)
summary(result_trim07_order3_coda)
```

```{r ,eval=FALSE}
ggplot(result_CI_t7o3, aes(x = variable, colour = setting)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2)
```

# alpha CI plot

```{r , fig.width=9, fig.height=8.5}
result_CI_t5o2$type = "t5o2"
result_CI_t6o2$type = "t6o2"
result_CI_t7o2$type = "t7o2"
result_CI_t5o3$type = "t5o3"
result_CI_t6o3$type = "t6o3"
result_CI_t7o3$type = "t7o3"

result_CI <- rbind(result_CI_t5o2,
                   result_CI_t6o2,
                   result_CI_t7o2,
                   result_CI_t5o3,
                   result_CI_t6o3,
                   result_CI_t7o3)

result_CI %>%
  mutate(across(type, factor,
                levels=c("t5o2","t6o2","t7o2",
                         "t5o3","t6o3","t7o3"))) %>%
  ggplot(aes(x = variable, colour = setting)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  facet_wrap(vars(type))
```

